### ISSUE TITLE
[OVERWOLF] Position not updating

### ISSUE THREAD

**Issue by EddyZuefflingen** [CptWesley/NewWorldMinimap#54] opened 2021-10-14 23:53 UTC
My position is static and wont change.

![image](https://user-images.githubusercontent.com/47632023/137410422-3189b1ba-0013-497e-b281-361e8f5fbc31.png)

3 Monitors
C# Application is running fine
Overwolf overlay is responsive and shows up when im ingame. Hides itself when tabbed out
No errors when compiling and importing app in to overwolf
Showing ingame fps is on #

**Comment by p1xel8ted** [comment] 2021-10-15 01:46
Replicated the issue for me as well. Completely uninstalled all traces of Overwolf and the app and reinstalled it, still have the same issue.

**Comment by CptWesley** [comment] 2021-10-15 07:33
Could you give some more details on the order of opening the applications? I cannot reproduce it locally.

**Comment by CptWesley** [comment] 2021-10-15 12:46
Overwolf changed their API, meaning it was no longer interpreting the values correctly and failing, thus showing the map on some debug coordinate. Should be fixed on current master branch.

**Closed as completed by CptWesley** 2021-10-15 12:46 UTC
Labels: bug, overwolf version
